# Generated by Django 3.0.4 on 2020-03-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_recipe_url_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Recipe intro',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Recipe title',
            new_name='title',
        ),
    ]
