# Generated by Django 3.0.4 on 2020-03-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20200322_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='steps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='cookbook.Ingredient'),
        ),
    ]
