# Generated by Django 3.0.4 on 2020-03-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20200322_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url_title',
            field=models.CharField(max_length=100),
        ),
    ]
