# Generated by Django 3.0.4 on 2020-03-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20200322_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Vegan'), (2, 'Veggie')], default=2),
        ),
    ]
