# Generated by Django 3.0.4 on 2020-03-22 14:05

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_recipe_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
