# Generated by Django 3.0.4 on 2020-03-22 14:45

import ckeditor.fields
from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_recipe_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, default='seedling', max_length=60),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
