# Generated by Django 3.0.4 on 2020-03-22 15:21

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_auto_20200322_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '500x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
