# Generated by Django 3.0.4 on 2020-03-22 19:15

import cloudinary.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_recipe_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1000x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
