# Generated by Django 3.0.4 on 2020-03-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_auto_20200322_2015'),
    ]

    def make_ingredient_lists(apps, schema_editor):
        Recipe = apps.get_model('cookbook', 'Recipe')
        Ingredient = apps.get_model('cookbook', 'Ingredient')
        IngredientList = apps.get_model('cookbook', 'IngredientList')
        for recipe in Recipe.objects.all():
            ingredients = Ingredient.objects.filter(recipe=recipe.id)
            ingredientlist = IngredientList(name="default", recipe=recipe)
            ingredientlist.save()
            for ingredient in ingredients:
                ingredient.ingredientlist = ingredientlist
                ingredient.save()

    operations = [
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientlists', to='cookbook.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredientlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookbook.IngredientList'),
            preserve_default=False,
        ),
        migrations.RunPython(make_ingredient_lists),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredientlist",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookbook.IngredientList'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
    ]
