# Generated by Django 3.0.4 on 2020-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0014_auto_20200324_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
