# Generated by Django 3.0.4 on 2020-03-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0015_auto_20200324_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
