# Generated by Django 3.0.4 on 2020-05-23 15:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0017_auto_20200325_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Ontbijt'), (2, 'Lunch'), (3, 'Avondmaal')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
