# Generated by Django 3.0.4 on 2020-08-02 08:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0018_auto_20200523_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Ontbijt'), (2, 'Lunch'), (3, 'Avondmaal'), (4, 'Dessert')], max_length=7, null=True),
        ),
    ]
