# Generated by Django 3.0.4 on 2020-11-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0019_auto_20200802_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='icon',
        ),
    ]
